name: Kubernetes Deploy
on:
  workflow_dispatch:
    inputs:
      repository-name:
        description: "repository to update"
        required: true
      tag_sha:
        description: "new sha tag value"
        required: false
      environment:
        description: deprecated
        required: false
      branch:
        description: triggered branch
        required: true
      user:
        description: runned job user
        required: true
jobs:
  deploy:
    environment: grimlock
    runs-on: ubuntu-latest
    name: Bump for deploy
    steps:
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: bump version
          commit_user_name: leonid korniienko
          commit_user_email: leo@pdffiller.com
          commit_author: leonid korniienko <leo@pdffiller.com>
          commit_options: "--no-verify --signoff"
